FORMAT: 1A

# UnderwriteMe API

## Overview
UnderwriteMe API is a set of REST endpoints which allows you to interact with underwriting workflow which consists of following components:
  
  * Application
  * Enquiry
  * Quote
  * Basket
  * Activation

# Group Application
Notes related resources of the Application API

## Create new Application [/application]
Creating new Application based on sent Customers and Products JSON data. 

### Create new Application [POST]
+ Request Valid Application (application/json)

            {
                "customers":[
                    {
                        "id":"cus-001",
                        "name":"John",
                        "surname":"Doe",
                        "title":"MR",
                        "gender":"MALE",
                        "dateOfBirth":"1980-01-01",
                        "smoker":false,
                        "email":"john.doe@domain.com"
                    }
                ],
                "products":[
                    {
                        "type":"WHOLE_OF_LIFE",
                        "coverAmount":100000,
                        "livesAssured":[
                            {
                                "id":"cus-001"
                            }
                        ]
                    }
                ]
            }

+ Response 201 (application/json)

            {
                "id":"UME00000000",
                "customers":[
                    {
                        "id":"1001",
                        "name":"John",
                        "surname":"Doe",
                        "title":"MR",
                        "gender":"MALE",
                        "dateOfBirth":"1980-01-01",
                        "smoker":false,
                        "email":"john.doe@domain.com"
                    }
                ],
                "products":[
                    {
                        "id":"0001-0001",
                        "type":"WHOLE_OF_LIFE",
                        "coverAmount":100000,
                        "livesAssured":[
                            {
                                "id":"1001"
                            }
                        ]
                    }
                ]
            }

+ Request Invalid Product amount (application/json)

            {
                "customers":[
                    {
                        "id":"cus-001",
                        "name":"John",
                        "surname":"Doe",
                        "title":"MR",
                        "gender":"MALE",
                        "dateOfBirth":"1980-01-01",
                        "smoker":false,
                        "email":"john.doe@domain.com"
                    }
                ],
                "products":[
                    {
                        "type":"WHOLE_OF_LIFE",
                        "coverAmount":1000,
                        "livesAssured":[
                            {
                                "id":"cus-001"
                            }
                        ]
                    }
                ]
            }

+ Response 400 (application/json)

            {
                "products":[
                    {
                        "coverAmount":{
                            "message":"Minimum cover amount is £10000"
                        }
                    }
                ]
            }

## Retrieve existing Application [/application/{id}]
Retrieving existing Application identified by unique ID.

+ Parameters

    + id (required, string, `UME00000000`) ... Text `id` of the Application to perform action with. Has example value.

### Retrieve existing Application [GET]
+ Response 200 (application/json)
    
    + Body
    
            {
                "id":"UME00000000", 
                "customers":[
                    {
                        "id":"101",
                        "name":"John",
                        "surname":"Doe",
                        "title":"MR",
                        "gender":"MALE",
                        "dateOfBirth":"1980-01-01",
                        "smoker":false,
                        "email":"john.doe@domain.com"
                    }
                ],
                "products":[
                    {
                        "id":"0001-0001",
                        "type":"WHOLE_OF_LIFE",
                        "coverAmount":100000,
                        "livesAssured":[
                            {
                              "id":"1001"
                            }
                        ]
                    }
                ]
            }
